### ISSUE TITLE
Feature Request: Push Values on to a MQTT Queue

### ISSUE THREAD

**Issue by yonz2** [wcbonner/GoveeBTTempLogger#58]
Hi,

I'm working on a remote data logger, that logs data from my Govee sensors. I would like have the RPI put the values read at a certain interval on to a MQTT queue.

I'm not a CPP developer, so I can't implement it myself and submit a pull request for a patch.

I did look into it, though, and using the [Eclipse Paho Library](https://github.com/eclipse/paho.mqtt.cpp) and a few new parameters this should be a straight forward thing to do...

### Parameters
```
[MQTT]
MQTT_URI=myserver.athome.com  
MQTT_PORT=1883 
MQTT_Username=myMQTTuser
MQTT_Password=myMQTTpassword
MQTT_TOPIC_PREFIX=goveebttemplogger
MQTT_INTERVAL=300
```

The routine should then every `MQTT_INTERVAL` seconds send the latest reading from each device as a JSON payload to the MQTT Topic:  ` MQTT_TOPIC_PREFIX/<<Mac Address of Device>>`  (or use the filename prefix used for the log files, for consistency)

### JSON Payload
```json
{
  "temperature": 23.20,
  "humidity": 43.70,
  "battery": 100
}
```

On the other end we can then use e.g. [Home Assistant's MQTT Sensor](https://www.home-assistant.io/integrations/sensor.mqtt/) to process the data            

### Example Home Assistant configuration.yaml entry
```yaml
mqtt:
  sensor:
    - name: "Temperature"
      state_topic: "goveebttemplogger/gvh-A4C13876CCXX"
      suggested_display_precision: 1
      unit_of_measurement: "°C"
      value_template: "{{ value_json.temperature }}
    - name: "Humidity"
      state_topic: "goveebttemplogger/gvh-A4C13876CCXX"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"
    - name: "Battery"
      state_topic: "goveebttemplogger/gvh-A4C13876CCXX"
      unit_of_measurement: "%"
      value_template: "{{ value_json.battery }}"
```
(Note: This config is just a basic template, needs to be tuned to the respective HA installation)

Just a thought.....

Best regards,
Yonz
